package com.makers.makersbnb.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;


// tell Spring Boot this class is a controller
@RestController
public class StaticPageController {


//    tell Sprint Boot this method handles the 'GET "/"' request
    @GetMapping("/")
    public ModelAndView welcome() {

        ModelAndView modelAndView = new ModelAndView("/LandingPage");
//        for now imagine this value was generated by querying the database
        Integer nSpaces = 100;
//        this next line makes nSpace available in the template
        modelAndView.addObject("nSpaces", nSpaces);
//        Imagine these reviews were stored in a database
        String[] reviews = new String[] {"Awesome", "Nice", "Perfect"}; // String[] literal
        modelAndView.addObject("reviews", reviews);
//        num bookings
        Integer numBookings = 123;
        modelAndView.addObject("bookings", numBookings);

        return modelAndView;
    }

//    This method will handle the GET "/contactus" request and
//    return a fake email address
    @GetMapping("/contactus")
    public String contactUs() {
        return "fake@email.com";
    }

    @GetMapping("/termsandconditions")
    public String termsAndConditions() {
        return "Coming soon! In the meantime, please behave yourselves.";
    }

//    GET "/signup"
//    render page that says "Join now to become user number 57"
//    57 should be passed into the template from the controller
    @GetMapping("/signup")
    public ModelAndView signUp() {
        ModelAndView modelAndView = new ModelAndView("/SignUp");
        Integer nextUser = 57;
        modelAndView.addObject("nextUser", nextUser);
        return modelAndView;
    }
}
