package com.makers.makersbnb.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;


// tell Spring Boot this class is a controller
@RestController
public class StaticPageController {


//    tell Sprint Boot this method handles the 'GET "/"' request
    @GetMapping("/")
    public ModelAndView landingPage() {
        ModelAndView modelAndView = new ModelAndView("/LandingPage");
//        for now imagine this value was generated by querying the database
        Integer nSpaces = 100;
//        this next line makes nSpace available in the template
        modelAndView.addObject("nSpaces", nSpaces);
        return modelAndView;
    }

//    This method will handle the GET "/contactus" request and
//    return a fake email address
    @GetMapping("/contactus")
    public String contactUs() {
        return "fake@email.com";
    }

    @GetMapping("/termsandconditions")
    public String termsAndConditions() {
        return "Coming soon! In the meantime, please behave yourselves.";
    }
}
